# Generated by Django 4.0.5 on 2022-07-01 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_nome_produto_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='marca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.marca'),
        ),
    ]
